apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: console
    name: console
    namespace: nsolid
  spec:
    progressDeadlineSeconds: 2147483647
    replicas: 1
    revisionHistoryLimit: 2147483647
    selector:
      matchLabels:
        app: console
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: console
      spec:
        containers:
        - env:
          - name: NSOLID_CONSOLE_DATA_DIR
            value: /var/lib/nsolid/console/data
          - name: NSOLID_CONSOLE_LOGS_INFLUX
            value: /var/lib/nsolid/console/influxdb.log
          image: nodesource/nsolid-console:carbon-latest
          imagePullPolicy: IfNotPresent
          name: console
          ports:
          - containerPort: 9001
            name: command
            protocol: TCP
          - containerPort: 9002
            name: data
            protocol: TCP
          - containerPort: 9003
            name: bulk
            protocol: TCP
          - containerPort: 6753
            name: console
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: nginx-secure-proxy
    name: nginx-secure-proxy
    namespace: nsolid
  spec:
    progressDeadlineSeconds: 2147483647
    replicas: 1
    revisionHistoryLimit: 2147483647
    selector:
      matchLabels:
        app: nginx-secure-proxy
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: nginx-secure-proxy
      spec:
        containers:
        - image: nodesource/nsolid-nginx:stable
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: nginx-secure-proxy
          ports:
          - containerPort: 10080
            protocol: TCP
          - containerPort: 10443
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/nginx/
            name: nginx-config
          - mountPath: /etc/nginx/ssl/
            name: nginx-tls
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: nginx-tls
          secret:
            defaultMode: 420
            secretName: nginx-tls
        - configMap:
            defaultMode: 420
            name: nginx-config
          name: nginx-config
  status: {}
kind: List
metadata: {}
