apiVersion: v1
kind: PersistentVolumeClaimList
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      namespace: nsolid
      name: nsolid-console
    spec:
      accessModes:
        - ReadWriteOnce 
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: console
    name: console
    namespace: nsolid
  spec:
    progressDeadlineSeconds: 2147483647
    replicas: 1
    revisionHistoryLimit: 2147483647
    selector:
      matchLabels:
        app: console
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: console
      spec:
        containers:
        - env:
          - name: NSOLID_CONSOLE_DATA_DIR
            value: /var/lib/nsolid/console/data
          - name: NSOLID_CONSOLE_LOGS_INFLUX
            value: /var/lib/nsolid/console/influxdb.log
          image: nodesource/nsolid-console:erbium-latest
          imagePullPolicy: IfNotPresent
          name: console
          ports:
          - containerPort: 9001
            name: command
            protocol: TCP
          - containerPort: 9002
            name: data
            protocol: TCP
          - containerPort: 9003
            name: bulk
            protocol: TCP
          - containerPort: 6753
            name: console
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/nsolid
            name: nsolid-console
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 16753
        terminationGracePeriodSeconds: 30
        volumes:
        - name: nsolid-console
          persistentVolumeClaim:
            claimName: nsolid-console
  status: {}
kind: List
metadata: {}
